"""Add ON DELETE CASCADE

Revision ID: e469ff2440f3
Revises: 328b67833644
Create Date: 2026-07-03 18:38:56.127371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e469ff2440f3'
down_revision: Union[str, Sequence[str], None] = '328b67833644'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ai_logs_chat_id_fkey'), 'ai_logs', type_='foreignkey')
    op.drop_constraint(op.f('ai_logs_user_id_fkey'), 'ai_logs', type_='foreignkey')
    op.create_foreign_key(None, 'ai_logs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'ai_logs', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('audit_logs_admin_id_fkey'), 'audit_logs', type_='foreignkey')
    op.create_foreign_key(None, 'audit_logs', 'users', ['admin_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('chats_user_id_fkey'), 'chats', type_='foreignkey')
    op.create_foreign_key(None, 'chats', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('document_chunks_document_id_fkey'), 'document_chunks', type_='foreignkey')
    op.create_foreign_key(None, 'document_chunks', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('documents_owner_id_fkey'), 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('messages_chat_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_chat_id_fkey'), 'messages', 'chats', ['chat_id'], ['id'])
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('documents_owner_id_fkey'), 'documents', 'users', ['owner_id'], ['id'])
    op.drop_constraint(None, 'document_chunks', type_='foreignkey')
    op.create_foreign_key(op.f('document_chunks_document_id_fkey'), 'document_chunks', 'documents', ['document_id'], ['id'])
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.create_foreign_key(op.f('chats_user_id_fkey'), 'chats', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.create_foreign_key(op.f('audit_logs_admin_id_fkey'), 'audit_logs', 'users', ['admin_id'], ['id'])
    op.drop_constraint(None, 'ai_logs', type_='foreignkey')
    op.drop_constraint(None, 'ai_logs', type_='foreignkey')
    op.create_foreign_key(op.f('ai_logs_user_id_fkey'), 'ai_logs', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('ai_logs_chat_id_fkey'), 'ai_logs', 'chats', ['chat_id'], ['id'])
    # ### end Alembic commands ###
